import type { Metadata } from "next";
import { Inter, Krona_One, Lora } from "next/font/google";
import "./globals.css";



const inter = Inter({
  variable: "--font-inter",
  weight: ["100","200","300","400","500","600","700","800"],
});

const kronaOne = Krona_One({
  variable: "--font-krona-one",
  weight: "400",
});

const lora = Lora({
  variable: "--font-lora",
  weight: ["400", "500", "600", "700"],
  // subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${kronaOne.variable} ${lora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
